{
 "title": "Cache Containment",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Incoming request rate (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(api_requests_started_total[15s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache hits throughput (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "targets": [
    { "expr": "rate(cache_hits_total[15s])", "legendFormat": "rate(cache_hits_total[15s])" }
   ]
  },
  {
   "title": "Cache misses throughput (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "targets": [
    { "expr": "rate(cache_misses_total[15s])", "legendFormat": "rate(cache_misses_total[15s])" }
   ]
  },
  {
   "title": "Cache in-flight load operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "targets": [
    { "expr": "cache_in_flight_loads", "legendFormat": "cache_in_flight_loads" }
   ]
  },
  {
   "title": "DB active connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    { "expr": "db_pool_active_connections", "legendFormat": "db_pool_active_connections" }
   ]
  },
  {
   "title": "DB waiting connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    { "expr": "db_pool_waiting_connections", "legendFormat": "db_pool_waiting_connections" }
   ]
  },
  {
   "title": "API p95 latency (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.95,\n  rate(api_request_latency_seconds_bucket[15s])\n)",
     "legendFormat": "histogram_quantile(0.95,   rate(api_request_latency_seconds_bucket[15s]))"
    }
   ]
  },
  {
   "title": "API Failure Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "(\n  sum(rate(api_requests_failed_total[15s]))\n  or vector(0)\n)\n/\nclamp_min(sum(rate(api_requests_started_total[15s])), 1)",
     "legendFormat": "sum(rate(api_requests_failed_total[15s])) /sum(rate(api_requests_started_total[15s]))"
    }
   ]
  }
 ]
}